# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-31 07:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sixerrapp', '0002_gig'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='slogan',
            field=models.CharField(default='My Slogan', max_length=500),
            preserve_default=False,
        ),
    ]
